Update misc/check-hardlinks
Also ask whether or not to diff when fixing diverged files (-d):
* if told not to diff: fix
* if told to diff: ask whether or not to fix

diff --git a/misc/check-hardlinks b/misc/check-hardlinks
--- a/misc/check-hardlinks
+++ b/misc/check-hardlinks
@@ -7,7 +7,7 @@
 # linking inconsistencies.                                                  #
 #                                                                           #
 # Version history:                                                          #
-#   v0.6a   Add --diff to diff diverged files                               #
+#   v0.6b   Add --diff to diff diverged files                               #
 #   v0.5    Add --fix-broken to replace the deprecated --fix option         #
 #           Add --fix-unreachable to fix unreachable files                  #
 #           Revamp return code mechanism                                    #
@@ -37,7 +37,7 @@ bashmod die
 bashmod tilde
 
 # Define some constants
-version=0.6a
+version=0.6b
 
 
 # Define some helper functions
@@ -52,10 +52,11 @@ function checklog() { # 1:code 2:message 3:file 4:reference
         then
             local black='\E[0m'         # Not real black: default setting, in fact
             local green='\E[1;32;32m'   # Bold green color
+            local blue='\E[1;34;34m'    # Bold blue color
             local red='\E[1;31;31m'     # Bold red color
 
             local color
-            (( $1 == 0 )) && color="$green" || color="$red"
+            (( $1 < 0 )) && color="$blue" || { (( $1 == 0 )) && color="$green" || color="$red" ; }
         fi
 
         printf "[${color}*${black}] %-${malign}s %-${falign}s" "$2" "$3"
@@ -63,6 +64,34 @@ function checklog() { # 1:code 2:message 3:file 4:reference
     fi
 
     rc=$(($rc | $1))
+}
+
+# askdiff: ask and diff 2 files
+function askdiff() { # 1:reffile 2:file
+    local ret=1                     # Return code
+    declare -a origdiffcommand      # User-provided diff command
+    declare -a diffcommand          # Instanciated diff command
+
+    # Ask the user first
+    read -p "Diff file? [y/N] " -r -u 3 ans
+    if [[ "${ans,,}" =~ ^y(es)?$ ]]
+    then
+        # Load the command into an array
+        read -a origdiffcommand -r <<< "$diff"
+
+        # Substitute the %REF and %LINK patterns in the command
+        diffcommand=("${origdiffcommand[@]//%REF/$1}")
+        diffcommand=("${diffcommand[@]//%LINK/$2}")
+        [[ "${diffcommand[*]}" == "${origdiffcommand[*]}" ]] && diffcommand+=("$1" "$2")
+
+        # Run the command
+        eval "${diffcommand[@]}" <&3
+
+        echo
+        return 0
+    fi
+
+    return 1
 }
 
 
@@ -233,30 +262,35 @@ do
                     # Files have diverged
                     if $fixdiverged
                     then
-                        rm "$f"
-                        ln "$file" "$f"
-                        checklog 0 "Fixed diverged file:" "$fn" "$filen"
-                        fix=1
-                    else
-                        checklog 4 "Diverged file:" "$fn" "$filen"
-
-                        # Offer to diff
+                        # Maybe diff
+                        dofix=true
                         if [[ -n "$diff" ]]
                         then
-                            # Ask the user first
-                            read -p "Diff files? [y/N] " -r -u 3 ans
-                            if [[ "${ans,,}" =~ ^y(es)?$ ]]
+                            # Report
+                            checklog -1 "Diverged file:" "$fn" "$filen"
+                            # Diff
+                            if askdiff "$filen" "$fn"
                             then
-                                # Load the command into an array
-                                read -a origdiffcommand -r <<< "$diff"
-                                # Substitute the %REF and %LINK patterns in the command
-                                diffcommand=("${origdiffcommand[@]//%REF/$filen}")
-                                diffcommand=("${diffcommand[@]//%LINK/$fn}")
-                                [[ "${diffcommand[*]}" == "${origdiffcommand[*]}" ]] && diffcommand+=("$filen" "$fn")
-                                # Run the command
-                                eval "${diffcommand[@]}" <&3
+                                # Ask
+                                read -p "Fix diverged file? [Y/n] " -r -u 3 ans
+                                [[ "${ans,,}" =~ ^n(o)?$ ]] && dofix=false
                             fi
-                            echo
+                        fi
+                        # Maybe fix
+                        if $dofix
+                        then
+                            rm "$f"
+                            ln "$file" "$f"
+                            checklog 0 "Fixed diverged file:" "$fn" "$filen"
+                            fix=1
+                        else
+                            checklog 4 "Diverged file:" "$fn" "$filen"
+                        fi
+                    else
+                        checklog 4 "Diverged file:" "$fn" "$filen"
+                        if [[ -n "$diff" ]]
+                        then
+                            askdiff "$filen" "$fn"
                         fi
                     fi
                 fi
