git/git-autobundle: fix error-handling

diff --git a/git/git-autobundle b/git/git-autobundle
--- a/git/git-autobundle
+++ b/git/git-autobundle
@@ -2,11 +2,11 @@
 
 die() {
     local rc=$?
-    printf "error: ${@[0]}\n" "${@:1}" >&2
+    echo "error: $*"
     exit $rc
-}
+} >&2
 
-if [[ "$1" =~ ^(-h|--help)$ ]]; then
+if [[ -z "$1" || "$1" =~ ^(-h|--help)$ ]]; then
     printf "usage: git autobundle <repo> [<bundle>]\n" >&2
     exit 0
 fi
