Update bash/functions/path
* Improve options processing (no more logic deduplication)
* Add --reset option to forget custom paths
* Fix bug with custom paths added several times to the list
* Fix local variables leaking into caller environment

diff --git a/bash/functions/path b/bash/functions/path
--- a/bash/functions/path
+++ b/bash/functions/path
@@ -22,11 +22,15 @@ function path() {
         echo "  prepend         prepend DIRS to the path"
         echo "  strip           strip DIRS from the path"
         echo
-        echo "Options:"
-        echo "  -g|--glob       when stripping, also strip when only"
-        echo "                  part of an entry is matched"
+        echo "Generic options:"
         echo "  -e|--export     export the environment variable"
         echo "  -v|--verbose    print the resulting path"
+        echo
+        echo "Specific options for action 'show':"
+        echo "  -r|--reset      forget non-default variables"
+        echo
+        echo "Specific options for action 'strip':"
+        echo "  -g|--glob       also strip when only part of an entry is matched"
         echo
         echo "Path variables:"
         echo "  bin   -> PATH"
@@ -46,7 +50,7 @@ function path() {
     #                 the user strips "/usr/bin" from its path
 
     # Enable extended globbing if needed
-    local CLEAR_EXTGLOB=""
+    local CLEAR_EXTGLOB=
     if ! shopt extglob &> /dev/null
     then
         CLEAR_EXTGLOB='true'
@@ -54,102 +58,108 @@ function path() {
     fi
 
     # Get action from arguments
-    local ACTIONS="$1"
-    case "$ACTIONS" in
-        "show"|"append"|"prepend"|"strip")
+    local SELECTED_ACTION="$1"
+    local ACTIONS=
+    case "$SELECTED_ACTION" in
+        "show"|"strip")
+            ACTIONS="$SELECTED_ACTION"
+            ;;
+
+        "append"|"prepend")
+            # Add 'strip' action before 'prepend' or 'append' to make sure DIRS are not in the path anymore
+            ACTIONS="strip $SELECTED_ACTION"
             ;;
 
         *)
-            echo "Error: unknown action '$1'!" >&2
+            echo "Error: unknown action '$SELECTED_ACTION'!" >&2
             return 1
             ;;
     esac
     shift
 
-    # Add 'strip' action before 'prepend' or 'append' to make sure DIRS are not in the path anymore
-    [[ "$ACTIONS" == "prepend" || "$ACTIONS" == "append" ]] && ACTIONS="strip $ACTIONS"
-
     # Parse options
-    local VERBOSE=''
-    local EXPORT=''
-    local GLOB=''
-    local OPTS_DONE=''
+    local EXPORT=
+    local GLOB=
+    local RESET=
+    local VERBOSE=
+    local OPTS_DONE=
     until [[ "$OPTS_DONE" ]]
     do
+        # Extract option
+        local OPTION='ERROR'
         case "$1" in
-            # Long options
+            # Long option
             --*)
-                case "$1" in
-                    "--verbose")
-                        VERBOSE='true'
-                        ;;
-
-                    "--export")
-                        EXPORT='true'
-                        ;;
-
-                    "--globbing")
-                        GLOB='true'
-                        ;;
-
-                    "--")
-                        OPTS_DONE='true'
-                        ;;
-
-                    *)
-                        echo "Error: unkown option '$1'!" >&2
-                        return 1
-                        ;;
-                esac
+                # Extract the option name
+                OPTION="${1:2}"
                 shift
                 ;;
 
-            # Short options
+            # Short option
             -*)
+                # Test for empty option
                 if [[ "$1" == "-" ]]
                 then
                     echo "Error: empty option flag '$1'!" >&2
                     return 1
                 fi
 
-                local SHORT_OPTS="${1#-}"
-                while [[ "$SHORT_OPTS" ]]
-                do
-                    case "${SHORT_OPTS::1}" in
-                        v)
-                            VERBOSE='true'
-                            ;;
-
-                        e)
-                            EXPORT='true'
-                            ;;
-
-                        g)
-                            GLOB='true'
-                            ;;
-
-                        *)
-                            echo "Error: unkown option '${SHORT_OPTS::1}'!" >&2
-                            return 1
-                            ;;
-                    esac
-                    SHORT_OPTS="${SHORT_OPTS#${SHORT_OPTS::1}}"
-                done
-                shift
+                # Extract the option short name
+                OPTION="${1:1:1}"
+                # Test if any options are left
+                if [[ -z "${1:2}" ]]
+                then
+                    # No more options here: shift
+                    shift
+                else
+                    # Reset the positional parameters without the current option
+                    set - "-${1:2}" "${@:2}"
+                    # Don't shift yet
+                fi
                 ;;
 
-            # No options
+            # Not an option
             *)
+                OPTION=
+                ;;
+        esac
+
+        # Process option
+        case "$OPTION" in
+            "e"|"export")
+                EXPORT='true'
+                ;;
+
+            "g"|"glob")
+                GLOB='true'
+                [[ "$ACTIONS" != "strip" ]] && { echo "Error: invalid option '$OPTION' for action '$SELECTED_ACTION'!" >&2 ; return 1 ; }
+                ;;
+
+            "r"|"reset")
+                RESET='true'
+                [[ "$ACTIONS" != "show" ]] && { echo "Error: invalid option '$OPTION' for action '$SELECTED_ACTION'!" >&2 ; return 1 ; }
+                ;;
+
+            "v"|"verbose")
+                VERBOSE='true'
+                ;;
+
+            "")
                 OPTS_DONE='true'
                 ;;
+
+            *)
+                echo "Error: unkown option '$OPTION'!" >&2
+                return 1
         esac
     done
 
     # Get target path variable
-    local TARGETS=""
+    local TARGETS=
     if [[ "$ACTIONS" == "show" && -z "$1" ]]
     then
-        # Show: if no specified path variable, show all path variables (including custom ones)
+        # Show action with no path specified: show all path variables (including custom ones, except if reset)
+        [[ "$RESET" ]] && unset PATH_CUSTOM_VARIABLES
         TARGETS="PATH LD_LIBRARY_PATH PKG_CONFIG_PATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH MANPATH ${PATH_CUSTOM_VARIABLES[@]}"
     else
         case "$1" in
@@ -175,8 +185,24 @@ function path() {
 
             *([[:word:]])PATH)
                 TARGETS=$1
-                # Remember the variable for later display with 'show' (this is NOT a local variable!)
-                PATH_CUSTOM_VARIABLES+=($1)
+
+                # Look for this path variable in the list of custom path variables
+                local FOUND=
+                local K
+                for K in "${!PATH_CUSTOM_VARIABLES[@]}"
+                do
+                    # Found it
+                    [[ "${PATH_CUSTOM_VARIABLES[$K]}" == "$TARGETS" ]] && { FOUND="$K" ; break ; }
+                done
+                # Check whether the path variable was found
+                if [[ "$FOUND" ]]
+                then
+                    # Forget this path if the --reset option has been given
+                    [[ "$RESET" ]] && unset PATH_CUSTOM_VARIABLES[$FOUND]
+                else
+                    # Remember the variable for later display with 'show' (this is NOT a local variable!)
+                    PATH_CUSTOM_VARIABLES+=("$TARGETS")
+                fi
                 ;;
 
             *)
@@ -188,9 +214,10 @@ function path() {
     shift
 
     # Process actions
-    for a in $ACTIONS
+    local A
+    for A in $ACTIONS
     do
-        case "$a" in
+        case "$A" in
             # Show: force verbose
             "show")
                 VERBOSE='true'
@@ -202,33 +229,37 @@ function path() {
                 [[ -z "$1" ]] && { echo "Error: empty directory path in DIRS!" >&2 ; return 1 ; }
                 local NEWPATH="$1"
                 shift
-                for d in "$@"
+                local D
+                for D in "$@"
                 do
-                    [[ -z "$d" ]] && { echo "Error: empty directory path in DIRS!" >&2 ; return 1 ; }
-                    NEWPATH="$NEWPATH:$d"
+                    [[ -z "$D" ]] && { echo "Error: empty directory path in DIRS!" >&2 ; return 1 ; }
+                    NEWPATH="$NEWPATH:$D"
                 done
 
                 # Add new path directories list
-                for t in $TARGETS
+                local T
+                for T in $TARGETS
                 do
-                    [[ -z "${!t}" ]] && eval $t="$NEWPATH" || { [[ "$a" == "append" ]] && eval $t="${!t}:$NEWPATH" || eval $t="$NEWPATH:${!t}" ; }
+                    [[ -z "${!T}" ]] && eval $T="$NEWPATH" || { [[ "$A" == "append" ]] && eval $T="${!T}:$NEWPATH" || eval $T="$NEWPATH:${!T}" ; }
                 done
                 ;;
 
             # Strip: remove DIRS from the specified path variable
             "strip")
-                for t in $TARGETS
+                local T
+                for T in $TARGETS
                 do
                     # Trick: wrap the path in ':' and replace inner ':' with '::'
-                    local TEMPPATH=":${!t//:/::}:"
+                    local TEMPPATH=":${!T//:/::}:"
 
                     # Strip directories
-                    for d in "$@"
+                    local D
+                    for D in "$@"
                     do
                         # String remove ':DIR:' (that's why we need the enclosing ':' above ;
                         # the '::' are needed so that consecutive matching entries are also caught)
-                        local PATTERN=":$d:"
-                        [[ "$GLOB" ]] && PATTERN=":*([!:])$d*([!:]):"
+                        local PATTERN=":$D:"
+                        [[ "$GLOB" ]] && PATTERN=":*([!:])$D*([!:]):"
                         TEMPPATH="${TEMPPATH//$PATTERN/}"
                     done
 
@@ -238,7 +269,7 @@ function path() {
                     TEMPPATH="${TEMPPATH%:}"
 
                     # Assign the new path
-                    eval $t="$TEMPPATH"
+                    eval $T="$TEMPPATH"
                 done
                 ;;
         esac
@@ -247,18 +278,20 @@ function path() {
     # Export the variables
     if [[ "$EXPORT" ]]
     then
-        for t in $TARGETS
+        local T
+        for T in $TARGETS
         do
-            export $t
+            export $T
         done
     fi
 
     # Be verbose
     if [[ "$VERBOSE" ]]
     then
-        for t in $TARGETS
+        local T
+        for T in $TARGETS
         do
-            echo -e "${GREEN}$t =${BLACK} ${!t}"
+            echo -e "${GREEN}$T =${BLACK} ${!T}"
         done
     fi
 
