bash/functions/ssh: improve workaround for netblue30/firejail#1616
Also add back the no-Firejail behavior.

diff --git a/bash/functions/ssh b/bash/functions/ssh
--- a/bash/functions/ssh
+++ b/bash/functions/ssh
@@ -12,58 +12,103 @@ export SSH_AGENT_LIFETIME=8h
 
 
 function ssh-agent-test() {
-    (( $# != 1 )) && { echo "Usage: $FUNCNAME <env-file>" >&2 ; return 1 ; }
+    (( $# == 1 )) || { echo "Usage: $FUNCNAME <env-file>" >&2; return 1; }
 
     local ssh_agent_envfile="$1"
 
     # Test for the env file
-    [[ ! -f "$ssh_agent_envfile" ]] && return 1
+    [[ -f "$ssh_agent_envfile" ]] || return 1
 
     # Source env file
-    . "$ssh_agent_envfile" &>/dev/null
+    source "$ssh_agent_envfile" &>/dev/null
     # Test the agent
     ssh-add -l &>/dev/null
-    (( $? == 2 )) && return 1
+    (( $? != 2 )) || return 1
 
     # All checks passed: valid agent
     return 0
 }
 
 
+function ssh-agent-fix-firejail-pid() {
+    (( $# == 1 )) || { echo "Usage: $FUNCNAME <env-file>" >&2; return 1; }
+
+    # Checks
+    local ssh_agent_envfile="$1"
+    [[ -f "$ssh_agent_envfile" ]] || { echo "Error: $FUNCNAME: no such env-file: $ssh_agent_envfile"; return 1; }
+    [[ -S "$SSH_AUTH_SOCK" ]] || { echo "Error: $FUNCNAME: bad agent socket: $SSH_AUTH_SOCK"; return 1; }
+    [[ "$(readlink "$(command -v ssh-agent)")" == */firejail ]] || { echo "Error: $FUNCNAME: only designed to operate with Firejail'ed ssh-agent"; return 1; }
+
+    # Get the agent's PID (last one in the `--tree` output; $(()) strips leading whitespace)
+    local ssh_agent_pid=$(( $(firejail --tree | grep -F "$SSH_AUTH_SOCK" | cut -d: -f1 | tail -n1) ))
+    (( ssh_agent_pid )) || { echo "Error: $FUNCNAME: unable to determine agent PID"; return 1; }
+
+    # Substitute it in the envfile
+    sed -e 's/^SSH_AGENT_PID=[0-9]\+;/SSH_AGENT_PID='"$ssh_agent_pid"';/' -e 's/Agent pid [0-9]\+/Agent pid '"$ssh_agent_pid"'/' -i "$ssh_agent_envfile"
+
+    # Fix it in the environment
+    export SSH_AGENT_PID="$ssh_agent_pid"
+}
+
+
 function ssh-agent-respawn() {
-    (( $# != 1 )) && { echo "Usage: $FUNCNAME <env-file>" >&2 ; return 1 ; }
+    (( $# == 1 )) || { echo "Usage: $FUNCNAME <env-file>" >&2 ; return 1 ; }
 
     local ssh_agent_envfile="$1"
 
     # Kill all existing agents for the current user (we can't use `ssh-agent -k` because SSH_AGENT_PID may not be set,
     # and ssh-agent runs in Firejail anyway and can't kill anything outside of its jail)
     pkill -u "$USER" ssh-agent
-    # /!\ `killall ssh-agent` doesn't work here! For some reason it can't find any running ssh-agent processes.
+    # /!\ `killall ssh-agent` doesn't work: for some reason, it can't find any running ssh-agent processes
 
     # Now start the agent
-    # Since we are (or should be) running under Firejail, which doesn't behave well with ssh-agent (see netblue30/firejail#1616),
-    # we'll do things a bit differently:
-    # * create the temporary agent socket directory ourselves
-    # * start the agent in foreground mode (this is were Firejail will kick in), with its socket in the above temporary directory
-    # * export SSH_AUTH_SOCK and SSH_AGENT_PID ourselves
-    # This way, we control where the socket is, and don't need to rely on the envfile which may not be available since we must background ssh-agent ourselves. However, we still create the envfile, for other shells to use.
-    # SSH_AGENT_PID is the PID of the parent Firejail, but that's fine for the purpose of killing the agent.
-    local ssh_agent_socket  # don't assign yet, it would mangle the return code of mktemp
-    ssh_agent_socket="$(mktemp -d --tmpdir ssh-XXXXXXXXXX)/S.ssh-agent" || { printf 'Error: %s: mktemp' "$FUNCNAME"; return 1; }
-    ssh-agent -t "$SSH_AGENT_LIFETIME" -s -D -a "$ssh_agent_socket" >"$ssh_agent_envfile" & disown
-    export SSH_AUTH_SOCK="$ssh_agent_socket" SSH_AGENT_PID="$!"
+    # If Firejail is involved, we'll need to use some tricks
+    if [[ "$(readlink "$(command -v ssh-agent)")" != */firejail ]]; then
+        # No Firejail in sight, we should be safe just running the agent
+        ssh-agent -t "$SSH_AGENT_LIFETIME" -s >"$ssh_agent_envfile"
+        source "$ssh_agent_envfile"
 
-    # Add auto keys with year-long lifetime (except if leap year, ok)
-    # Since the agent process is detached, we're not sure yet that it's up and running. Hence we try to add the keys several times before giving up.
-    (
-        for ((i=0; i<10; i++)); do
-            ssh-add -t 365d "${SSH_AGENT_AUTOKEYS[@]}" &>/dev/null && exit
-            sleep 1
-        done
-        echo 'Warning: failed to add SSH_AGENT_AUTOKEYS after 10 tries'
-        exit 1
-    ) & disown
+        # Then we can just add the keys (this works fine even when the array is empty)
+        ssh-add -t 365d "${SSH_AGENT_AUTOKEYS[@]}" &>/dev/null
+    else
+        # So we're going to be running under Firejail, which doesn't behave well with ssh-agent (see netblue30/firejail#1616)
+        # We need to do things a bit differently:
+        # * create a temporary directory for the agent socket
+        # * start the agent (under Firejail), passing in the temporary directory, and have Bash background it
+        #   NB: using `ssh-agent -D` somehow doesn't work, as the process gets killed when the shell that spawned it exits;
+        #       however we don't really need `-D` since Firejail already prevents ssh-agent from backgrounding itself
+        # * export SSH_AUTH_SOCK and SSH_AGENT_PID
+        # This way, we control the socket's location, and don't need to rely on the envfile which may not be available
+        # (since we background ssh-agent ourselves). However, we still create the envfile, for other shells to use.
+        local ssh_agent_socket  # don't assign yet, it would mangle the return code of mktemp
+        ssh_agent_socket="$(mktemp -d --tmpdir ssh-XXXXXXXXXX)/S.ssh-agent" || { echo "Error: $FUNCNAME: mktemp"; return 1; }
+        ssh-agent -a "$ssh_agent_socket" -t "$SSH_AGENT_LIFETIME" -s >"$ssh_agent_envfile" & disown     # NB: keep in sync with sed expr below
+        export SSH_AUTH_SOCK="$ssh_agent_socket" SSH_AGENT_PID="$!"
+
+        # An issue remains in that the envfile will hold the PID of ssh-agent in its Firejail PID namespace, which is pretty
+        # much useless when it comes to killing the agent (from another shell that doesn't have the above SSH_AGENT_PID).
+        # So we must find out the PID of the child Firejail process or the agent (but not the parent Firejail process, which
+        # will die when this shell exits), and drop it in the envfile once the agent is running. We do all of this only once
+        # the agent is running, since before that Firejail may not have had any time to even just fully spawn yet (because &).
+        # We resort to polling in the background to wait for the agent to come up, which is fine since we already have all
+        # we need for our current shell's environment.
+        (
+            for ((i=0; i<10; i++)); do
+                if ssh-agent-test "$ssh_agent_envfile"; then
+                    # Agent is up!
+                    # Fix the PID in the envfile
+                    ssh-agent-fix-firejail-pid "$ssh_agent_envfile"
+                    # Add auto keys with year-long lifetime (except if leap year, ok)
+                    ssh-add -t 365d "${SSH_AGENT_AUTOKEYS[@]}" &>/dev/null
+                    exit 0
+                fi
+                sleep 1
+            done
+            echo "Warning: $FUNCNAME: ssh-agent still unreachable after 10 attempts"
+            exit 1
+        ) & disown
+        # NB: if the current shell dies before this background jobs completes, the envfile will retain the namespaced PID. That's life.
+    fi
 
     return 0
 }
-
