Update gentoo/kernel/genkernel-cobalt
* style overhaul
* use getopt
* make initramfs update for uvesafb optional (since nouveau)

diff --git a/gentoo/kernel/genkernel-cobalt b/gentoo/kernel/genkernel-cobalt
--- a/gentoo/kernel/genkernel-cobalt
+++ b/gentoo/kernel/genkernel-cobalt
@@ -12,13 +12,13 @@ bashmod die
 
 
 # Environment variables
-KERNELDIR="${KERNELDIR:-/usr/src/linux}"
-KERNELCONF="${KERNELCONF:-$KERNELDIR/.config.cobalt}"
+: "${KERNELDIR:=/usr/src/linux}"
+: "${KERNELCONF:=$KERNELDIR/.config.cobalt}"
+: "${GRUBCFG:=/boot/grub/grub.cfg}"
 
 
 # Display help
-if [[ "$1" == "-h" || "$1" == "--help" ]]
-then
+if [[ "$1" == "-h" || "$1" == "--help" ]] ; then
     cat <<- _EOF_
 	  Usage: ${0##*/} [options]
 	
@@ -26,13 +26,17 @@ then
 	support. Also strips the initramfs from unneeded stuff (modules and HW
 	detection logic).
 	
-	The kernel is configured and built in:
+	The kernel is configured and built in \$KERNELDIR (default "/usr/src/linux"):
 	    $KERNELDIR
-	using configuration:
+	using configuration \$KERNELCONF (default "\$KERNELDIR/.config/cobalt"):
 	    $KERNELCONF
-
-    Options:
-        -m | --no-emerge    don't emerge @module-rebuild
+	The Grub configuration file is \$GRUBCFG (default "/boot/grub/grub.cfg"):
+	    $GRUBCFG
+	
+	Options:
+	    -m | --no-emerge    don't emerge @module-rebuild
+	    -u | --uvesafb      perform additional steps (add v86d
+	                        to initramfs) for uvesafb
 	_EOF_
     exit
 fi
@@ -44,10 +48,11 @@ getopt="$(getopt -n "${0##*/}" -l no-emerge -o +m -- "$@")"
 (( $? != 0 )) && exit 1
 eval set -- "$getopt"
 emerge=true
-while true
-do
+uvesafb=false
+while true ; do
     case "$1" in
         -m|--no-emerge) emerge=false ;;
+        -u|--uvesafb) uvesafb=true ;;
         --) shift ; break ;;
         *) die "getopt failure" ;;
     esac
@@ -60,45 +65,45 @@ done
 genkernel --save-config --no-mrproper --clean --install --symlink --no-ramdisk-modules --no-all-ramdisk-modules --kerneldir="$KERNELDIR" --kernel-config="$KERNELCONF" --mountboot --makeopts="-j8" --no-keymap --splash="emerge-world" --splash-res="1920x1080" --lvm --no-mdadm --no-dmraid --no-luks --kernname="cobalt" --no-firmware --compress-initramfs-type="gzip" all
 
 
-# Append files to the initramfs
-if (( $? == 0 ))
-then
-    echo
-    echo
-    INITRAMFS="$(ls -ct -1 /boot/initramfs* | head -n 1)"    # use most recently touched initramfs
-    INITDIR="${0##*/}-initramfs"
-    IMPORTER="${0%/*}/import-initramfs"
-    if [[ -f "$INITRAMFS" && -x "$IMPORTER" ]]
-    then
-        echo "Including additional files into initramfs..."
-        mkdir -p "$INITDIR"
-        pushd "$INITDIR"
-        gunzip -c "$INITRAMFS" | cpio -i
-        popd
-        "$IMPORTER" /usr/share/v86d/initramfs "$INITDIR"
-        pushd "$INITDIR"
-        find . -print0 | cpio -0 -o -H newc | gzip -c -9 > "$INITRAMFS"
-        popd
-        rm -Rf "$INITDIR"
-    else
-        echo "ERROR: Cannot include additional files: importer not found, or initramfs not found"
+if (( $? == 0 )) ; then
+    # Append v86d files to the initramfs for uvesafb
+    if $uvesafb ; then
+        echo
+        echo
+        initramfs="$(ls -ct -1 /boot/initramfs* | head -n 1)"    # use most recently touched initramfs
+                                                                 # (yes, `ls` is bad: use [[ -nt ]] instead?)
+        initdir="${0##*/}-initramfs"
+        importer="${0%/*}/import-initramfs"
+        if [[ -f "$initramfs" && -x "$importer" ]] ; then
+            echo "Including additional files into initramfs..."
+            mkdir -p "$initdir"
+            pushd "$initdir"
+            gunzip -c "$initramfs" | cpio -i
+            popd
+            "$importer" /usr/share/v86d/initramfs "$initdir"
+            pushd "$initdir"
+            find . -print0 | cpio -0 -o -H newc | gzip -c -9 > "$initramfs"
+            popd
+            rm -Rf "$initdir"
+        else
+            die "cannot include additional files: importer not found, or initramfs not found"
+        fi
     fi
 
 
+    # Configure Grub
     echo
     echo
-    GRUBCFG="/boot/grub/grub.cfg"
     if [[ -f "$GRUBCFG" ]]
     then
         grub2-mkconfig -o "$GRUBCFG"
     else
-        echo "WARNING: Cannot update Grub: $GRUBCFG not found"
+        echo "Warning: cannot update Grub: '$GRUBCFG' not found" >&2
     fi
 fi
 
 # Emerge external modules
-if $emerge
-then
+if $emerge ; then
     echo
     echo
     emerge --quiet-build y -k @module-rebuild
