Update admin/network/fwall{,6}
Style overhaul.

diff --git a/admin/network/fwall b/admin/network/fwall
--- a/admin/network/fwall
+++ b/admin/network/fwall
@@ -2,79 +2,92 @@
 
 ## http://www.ibm.com/developerworks/edu/l-dw-linuxfw-i.html
 
-# Our complete stateful firewall script.  This firewall can be customized for
-# a laptop, workstation, router or even a server. :)
+# Our complete stateful firewall script. This firewall can be customized for a
+# laptop, workstation, router or even a server. :)
 
 # All your network interfaces, including lo.
-INTERFACES="lo eth0 wlan0"
+#interfaces=(lo eth0 wlan0)
+interfaces=(lo enp4s0 wlp0s29u1u8)
 
 # The interfaces that provides your "uplink".
-UPLINK="eth0 wlan0"
+#uplink=(eth0 wlan0)
+uplink=(enp4s0 wlp0s29u1u8)
 
 # The local (ie., trusted) interfaces.
-LOCAL="lo"
+local_interfaces=(lo)
 
 # Local network address range (with mask).
-LAN="192.168.1.0/24"
+lan="192.168.1.0/24"
 
-# Change this line so that it lists the assigned numbers or symbolic names (from
-# /etc/services) of all the services that you'd like to provide to the general
-# public.  If you don't want any services enabled, set it to "".
-SERVICES_TCP=""
-SERVICES_UDP=""
-LAN_SERVICES_TCP="ssh"
-LAN_SERVICES_UDP=""
+# Change this line so that it lists the assigned numbers or symbolic names
+# (from /etc/services) of all the services that you'd like to provide to the
+# general public. If you don't want any services enabled, set it to ().
+services_tcp=()
+services_udp=()
+lan_services_tcp=(ssh)
+lan_services_udp=()
+
+# Our default INPUT policy: DROP.
+default_input_policy=DROP
 
 
-function start_fw
-{
+function start_fw() {
     echo -n "Starting IPv4 firewall... "
 
-    # Input table default policy : DROP.
-    iptables -P INPUT DROP
+    local has_ssh_22=false
+
+    # Input table default policy.
+    iptables -P INPUT "$default_input_policy"
 
     # Accept local (trusted) traffic.
-    for x in ${LOCAL}
+    for i in "${local_interfaces[@]}"
     do
-        iptables -A INPUT -i ${x} -j ACCEPT
+        iptables -A INPUT -i "$i" -j ACCEPT
     done
 
     # Accept ESTABLISHED or RELATED connections.
     iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
 
     # Enable public access to global services.
-    for x in ${SERVICES_TCP}
+    for s in "${services_tcp[@]}"
     do
-        iptables -A INPUT -p tcp --dport ${x} -m conntrack --ctstate NEW -j LOG --log-prefix "[iptables] TCP service:"
-        iptables -A INPUT -p tcp --dport ${x} -m conntrack --ctstate NEW -j ACCEPT
+        iptables -A INPUT -p tcp --dport "$s" -m conntrack --ctstate NEW -j LOG --log-prefix "[iptables] $s TCP svc:"
+        iptables -A INPUT -p tcp --dport "$s" -m conntrack --ctstate NEW -j ACCEPT
+        # Check whether ssh is part of our service set
+        [[ "$s" == "ssh" ]] && has_ssh_22=true
     done
-    for x in ${SERVICES_UDP}
+    for s in "${services_udp[@]}"
     do
-        iptables -A INPUT -p udp --dport ${x} -m conntrack --ctstate NEW -j LOG --log-prefix "[iptables] UDP service:"
-        iptables -A INPUT -p udp --dport ${x} -m conntrack --ctstate NEW -j ACCEPT
+        iptables -A INPUT -p udp --dport "$s" -m conntrack --ctstate NEW -j LOG --log-prefix "[iptables] $s UDP svc:"
+        iptables -A INPUT -p udp --dport "$s" -m conntrack --ctstate NEW -j ACCEPT
     done
 
     # Enable LAN access to LAN services.
-    for x in ${LAN_SERVICES_TCP}
+    for s in "${lan_services_tcp[@]}"
     do
-        iptables -A INPUT -p tcp --dport ${x} -m conntrack --ctstate NEW -s ${LAN} -j LOG --log-prefix "[iptables] TCP lan-service:"
-        iptables -A INPUT -p tcp --dport ${x} -m conntrack --ctstate NEW -s ${LAN} -j ACCEPT
+        iptables -A INPUT -p tcp --dport "$s" -m conntrack --ctstate NEW -s "$lan" -j LOG --log-prefix "[iptables] $s TCP lan-svc:"
+        iptables -A INPUT -p tcp --dport "$s" -m conntrack --ctstate NEW -s "$lan" -j ACCEPT
+        # Check whether ssh is part of our service set
+        [[ "$s" == "ssh" ]] && has_ssh_22=true
     done
-    for x in ${LAN_SERVICES_UDP}
+    for s in "${lan_services_udp[@]}"
     do
-        iptables -A INPUT -p udp --dport ${x} -m conntrack --ctstate NEW -s ${LAN} -j LOG --log-prefix "[iptables] UDP lan-service:"
-        iptables -A INPUT -p udp --dport ${x} -m conntrack --ctstate NEW -s ${LAN} -j ACCEPT
+        iptables -A INPUT -p udp --dport "$s" -m conntrack --ctstate NEW -s "$lan" -j LOG --log-prefix "[iptables] $s UDP lan-svc:"
+        iptables -A INPUT -p udp --dport "$s" -m conntrack --ctstate NEW -s "$lan" -j ACCEPT
     done
 
     # Log and reject attempts at SSH connection on port 22 separately.
-    iptables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -j LOG --log-prefix "[iptables] ssh22fail:"
-    iptables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -j DROP
+    if ! $has_ssh_22
+    then
+        iptables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -j LOG --log-prefix "[iptables] ssh22fail:"
+        iptables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -j "$default_input_policy"
+    fi
 
     # Other rejected attempts.
     iptables -A INPUT -p tcp -j LOG --log-prefix "[iptables] bad TCP:"
     iptables -A INPUT -p udp -j LOG --log-prefix "[iptables] bad UDP:"
-    iptables -A INPUT -p tcp -j DROP
-    iptables -A INPUT -p udp -j DROP
+    iptables -A INPUT -p tcp -j "$default_input_policy"
+    iptables -A INPUT -p udp -j "$default_input_policy"
 
     # Only non-UDP/TCP eth0/wlan0 traffic might end up here: low-level traffic.
     iptables -A INPUT -j LOG --log-prefix "[iptables] bad other:"
@@ -82,17 +95,16 @@ function start_fw
     # Output table default policy: ACCEPT.
     iptables -P OUTPUT ACCEPT
 
-    # Disable spoofing on all interfaces.
-    for x in ${INTERFACES}
+    # Enable reverse path filtering on all interfaces.
+    for i in "${interfaces[@]}"
     do
-        echo 1 > /proc/sys/net/ipv4/conf/${x}/rp_filter
+        echo 1 > "/proc/sys/net/ipv4/conf/$i/rp_filter"
     done
 
     echo "done"
 }
 
-function stop_fw
-{
+function stop_fw() {
     echo -n "Stopping IPv4 firewall... "
 
     iptables -F INPUT
@@ -114,7 +126,6 @@ then
     stop_fw
     start_fw
 else
-    echo "SYNTAX: ${0##*/} <start|stop|restart>"
+    echo "Syntax: ${0##*/} <start|stop|restart>"
 fi
 
-exit 0
diff --git a/admin/network/fwall6 b/admin/network/fwall6
--- a/admin/network/fwall6
+++ b/admin/network/fwall6
@@ -2,64 +2,73 @@
 
 ## http://www.ibm.com/developerworks/edu/l-dw-linuxfw-i.html
 
-# Our complete stateful firewall script.  This firewall can be customized for
-# a laptop, workstation, router or even a server. :)
+# Our complete stateful firewall script. This firewall can be customized for a
+# laptop, workstation, router or even a server. :)
 
 # All your network interfaces, including lo.
-#INTERFACES="lo eth0 wlan0"
-INTERFACES="lo eth0"
+#interfaces=(lo eth0 wlan0)
+interfaces=(lo enp4s0 wlp0s29u1u8)
 
 # The interfaces that provides your "uplink".
-#UPLINK="eth0 wlan0"
-UPLINK="eth0"
+#uplink=(eth0 wlan0)
+uplink=(enp4s0 wlp0s29u1u8)
 
 # The local (ie., trusted) interfaces.
-LOCAL="lo"
+local_interfaces=(lo)
 
-# Change this line so that it lists the assigned numbers or symbolic names (from
-# /etc/services) of all the services that you'd like to provide to the general
-# public.  If you don't want any services enabled, set it to "".
-SERVICES_TCP=""
-SERVICES_UDP=""
+# Change this line so that it lists the assigned numbers or symbolic names
+# (from /etc/services) of all the services that you'd like to provide to the
+# general public. If you don't want any services enabled, set it to ().
+services_tcp=()
+services_udp=()
+
+# Our default INPUT policy: DROP.
+default_input_policy=DROP
 
 
-function start_fw6
-{
+function start_fw6() {
     echo -n "Starting IPv6 firewall... "
 
-    # Input table default policy : DROP.
-    ip6tables -P INPUT DROP
+    local has_ssh_22=false
+
+    # Input table default policy.
+    ip6tables -P INPUT "$default_input_policy"
 
     # Accept local (trusted) traffic.
-    for x in ${LOCAL}
+    for i in "${local_interfaces[@]}"
     do
-        ip6tables -A INPUT -i ${x} -j ACCEPT
+        ip6tables -A INPUT -i "$i" -j ACCEPT
     done
 
     # Accept ESTABLISHED or RELATED connections.
     ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
 
     # Enable public access to global services.
-    for x in ${SERVICES_TCP}
+    for s in "${services_tcp[@]}"
     do
-        ip6tables -A INPUT -p tcp --dport ${x} -m conntrack --ctstate NEW -j LOG --log-prefix "[ip6tables] TCP service:"
-        ip6tables -A INPUT -p tcp --dport ${x} -m conntrack --ctstate NEW -j ACCEPT
+        ip6tables -A INPUT -p tcp --dport "$s" -m conntrack --ctstate NEW -j LOG --log-prefix "[ip6tables] $s TCP svc:"
+        ip6tables -A INPUT -p tcp --dport "$s" -m conntrack --ctstate NEW -j ACCEPT
+        # Check whether ssh is part of our service set
+        [[ "$s" == "ssh" ]] && has_ssh_22=true
     done
-    for x in ${SERVICES_UDP}
+    for s in "${lan_services_udp[@]}"
     do
-        ip6tables -A INPUT -p udp --dport ${x} -m conntrack --ctstate NEW -j LOG --log-prefix "[ip6tables] UDP service:"
-        ip6tables -A INPUT -p udp --dport ${x} -m conntrack --ctstate NEW -j ACCEPT
+        ip6tables -A INPUT -p udp --dport "$s" -m conntrack --ctstate NEW -j LOG --log-prefix "[ip6tables] $s UDP svc:"
+        ip6tables -A INPUT -p udp --dport "$s" -m conntrack --ctstate NEW -j ACCEPT
     done
 
     # Log and reject attempts at SSH connection on port 22 separately.
-    ip6tables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -j LOG --log-prefix "[ip6tables] ssh22fail:"
-    ip6tables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -j DROP
+    if ! $has_ssh_22
+    then
+        ip6tables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -j LOG --log-prefix "[ip6tables] ssh22fail:"
+        ip6tables -A INPUT -p tcp --dport ssh -m conntrack --ctstate NEW -j "$default_input_policy"
+    fi
 
     # Other rejected attempts.
     ip6tables -A INPUT -p tcp -j LOG --log-prefix "[ip6tables] bad TCP:"
     ip6tables -A INPUT -p udp -j LOG --log-prefix "[ip6tables] bad UDP:"
-    ip6tables -A INPUT -p tcp -j DROP
-    ip6tables -A INPUT -p udp -j DROP
+    ip6tables -A INPUT -p tcp -j "$default_input_policy"
+    ip6tables -A INPUT -p udp -j "$default_input_policy"
 
     # Accept ICMPv6 packets, which are required for MAC address resolution.
     ip6tables -A INPUT -p icmpv6 -j ACCEPT
@@ -73,8 +82,7 @@ function start_fw6
     echo "done"
 }
 
-function stop_fw6
-{
+function stop_fw6() {
     echo -n "Stopping IPv6 firewall... "
 
     ip6tables -F INPUT
@@ -96,7 +104,6 @@ then
     stop_fw6
     start_fw6
 else
-    echo "SYNTAX: ${0##*/} <start|stop|restart>"
+    echo "Syntax: ${0##*/} <start|stop|restart>"
 fi
 
-exit 0
