Update audio/freebox-title-fix
Add options --quiet and --reverse.
Also some coding style changes.

diff --git a/audio/freebox-title-fix b/audio/freebox-title-fix
--- a/audio/freebox-title-fix
+++ b/audio/freebox-title-fix
@@ -1,10 +1,18 @@
 #!/bin/bash
 # "Fix" the title tags of audio tracks by prepending them with the track #
 
-if [[ $# -lt 1 || "$1" == "-h" || "$1" == "--help" ]]
+# Build full name
+[[ "${0:0:1}" == "/" ]] && full_0="$0" || full_0="$PWD/$0"
+
+# Source required modules (bashmod first, then use it for the others)
+[[ ! -r "${BASH_MODULES_SCRIPT=${full_0%/*}/../bash/modules/bashmod}" ]] && { printf "Error: This script requires the 'bashmod' module, please specify its path\n       with the BASH_MODULES_SCRIPT environment variable.\n" ; exit 255 ; }
+source "$BASH_MODULES_SCRIPT"
+bashmod die
+
+if (( $# < 1 )) || [[ "$1" =~ ^(-h|--help)$ ]]
 then
-    cat <<- _EOF_
-	  Usage: ${0##*/} <directories>
+    cat <<- EOF
+	  Usage: ${0##*/} [options] <directories>
 	
 	Prepend the track # to the title tag of audio tracks in a directory.
 	For MP3, also convert the id3 tags to v2.4, stripping all other versions.
@@ -14,14 +22,18 @@ then
 	    ogg
 	    flac
 	
+	Options:
+	    -q | --quiet        proceed without confirmation
+	    -R | --reverse      do the reverse: strip the track # from the title tag
+	
 	Note:
 	* The first space-delimited block of characters in the filename is assumed to
 	  be the track # (this is highly tied to the organization of my library).
-	* The main purpose of this tool is to work around a misfeature of my ISP's
-	  shitty DLNA music player, which orders tracks alphabetically by title tag
-	  -- not even by filename! *sigh*
+	* The main purpose of this tool is to work around a misfeature in the
+	  shitty DLNA music player of my ISP's set-top box, which orders tracks
+	  alphabetically by title tag -- not even by filename! *sigh*
 	
-	_EOF_
+	EOF
     exit
 fi
 
@@ -49,33 +61,18 @@ function require() {    #1:tool [2:variable] [3+:paths]
         fi
     done
 
-    echo "Error: the \`$tool\` utility is required but not found in your PATH!" >&2
-    exit 1
-}
-
-function trackno() {    #1:file
-    printf "${1%% *}"
+    die "the \`$tool\` utility is required but not found in your PATH!"
 }
 
 function tracktitle() { #1:file [2:escape]
     local title
     case "${1##*.}" in
-        mp3)
-            title="$($id3ted -l "$1" | sed -ne '/^TIT2:/ s/TIT2: //p')"
-            ;;
-        ogg)
-            title="$($vorbiscomment -l "$1" | sed -ne '/^title=/ s/title=//p')"
-            ;;
-        flac)
-            title="$($metaflac --list "$1" | sed -ne '/^ *comment\[[0-9]\+\]: TITLE=/ s/^.*=//p')"
-            ;;
+        mp3) title="$($id3ted -l "$1" | sed -ne '/^TIT2:/ s/TIT2: //p')" ;;
+        ogg) title="$($vorbiscomment -l "$1" | sed -ne '/^title=/ s/title=//p')" ;;
+        flac) title="$($metaflac --list "$1" | sed -ne '/^ *comment\[[0-9]\+\]: TITLE=/ s/^.*=//p')" ;;
     esac
-    if (( ${2:-0} ))
-    then
-        sed -e 's,/,\/,g' -e 's/&/\&/g' <<< "$title"
-    else
-        echo "$title"
-    fi
+    $reverse && title="${title#* - }" || title="${1%% *} - $title"
+    ${2:-false} && sed -e 's/\\/\\\\/g' -e 's,/,\/,g' -e 's/&/\&/g' <<< "$title" || echo "$title"
 }
 
 # Check for required utilities
@@ -91,8 +88,29 @@ shopt -s nullglob
 shopt -s nocaseglob
 shopt -s nocasematch
 
-quiet=0
+# Parse command line
+getopt -T &> /dev/null
+(( $? != 4 )) && die -r128 "your getopt version is too old, get the enhanced getopt from util-linux!"
+getopt="$(getopt -n "${0##*/}" -l quiet,reverse -o qR -- "$@")"
+(( $? != 0 )) && exit 128
+eval set -- "$getopt"
 
+# Process options
+quiet=false
+reverse=false
+while true
+do
+    case "$1" in
+        -q|--quiet) quiet=true ;;
+        -R|--reverse) reverse=true ;;
+        --) shift ; break ;;
+        *) die -r128 "internal error!" ;;
+    esac
+    shift
+done
+
+# Process directories
+(( $# < 1 )) && die -r128 "missing directories"
 for d in "$@"
 do
     if ! [[ -d "$d" ]]
@@ -102,63 +120,58 @@ do
     fi
     cd "$d"
     d="${d%/}"
-    proceed=1
-    refresh=1
-    empty=1
-    if ! (( $quiet ))
+    proceed=true
+    refresh=true
+    empty=true
+    if ! $quiet
     then
-        while (( $refresh ))
+        while $refresh
         do
-            refresh=0
+            refresh=false
             printf "Overview for '%s':" "$d"
             for f in *.mp3 *.ogg *.flac
             do
-                empty=0
-                printf "\n  %s - %s" "$(trackno "$f")" "$(tracktitle "$f")"
+                empty=false
+                printf "\n  %s" "$(tracktitle "$f")"
             done
-            if (( $empty ))
+            if $empty
             then
                 printf "\E[2K\rSkipping '%s': no tracks\n" "$d"
-                proceed=0
+                proceed=false
             else
                 echo
-                read -r -p "Proceed? [y/N/r] " proceed
-                case "$proceed" in
-                    y|Y) proceed=1 ;;
-                    n|N) proceed=0 ;;
-                    r|R) refresh=1 ;;
+                read -r -p "Proceed? [y/N/r] " ans
+                case "${ans,,}" in
+                    y|yes) proceed=true ;;
+                    r|refresh) refresh=true ;;
+                    *) proceed=false ;;
                 esac
             fi
         done
     fi
-    if (( $proceed ))
+    if $proceed
     then
         for f in *.mp3 *.ogg *.flac
         do
-            empty=0
+            empty=false
             printf "\E[2K\rProcessing '%s'... %s" "$d" "$f"
             case "${f##*.}" in
                 mp3)
                     $id3ted -2 "$f"
-                    $id3ted -t "$(trackno "$f") - $(tracktitle "$f")" "$f"
+                    $id3ted -t "$(tracktitle "$f")" "$f"
                     $id3ted -s "$f"
                     ;;
                 ogg)
-                    $vorbised 's/^title=\(.*\)/title='"$(trackno "$f" 1)"' - '"$(tracktitle "$f" 1)"'/' "$f"
+                    $vorbised 's/^title=\(.*\)/title='"$(tracktitle "$f" true)"'/' "$f"
                     ;;
                 flac)
-                    $sedaflac 's/^TITLE=\(.*\)/TITLE='"$(trackno "$f" 1)"' - '"$(tracktitle "$f" 1)"'/' "$f"
+                    $sedaflac 's/^TITLE=\(.*\)/TITLE='"$(tracktitle "$f" true)"'/' "$f"
                     ;;
             esac
         done
-        if (( $empty ))
-        then
-            printf "Skipping '%s': no tracks\n" "$d"
-        else
-            printf "\E[2K\rProcessing '%s'... done\n" "$d"
-        fi
+        $empty && printf "Skipping '%s': no tracks\n" "$d" || printf "\E[2K\rProcessing '%s'... done\n" "$d"
     fi
-    (( $quiet )) || echo
+    $quiet || echo
     cd "$OLDPWD"
 done
 
