Update misc/check-hardlinks, admin/safeshutdown, admin/gentoo/purge-distfiles
Switch to bashmod to source required Bash modules. Use sensible defaults
for BASH_MODULES_SCRIPT to avoid having to set it in the repo
environment.

diff --git a/admin/gentoo/purge-distfiles b/admin/gentoo/purge-distfiles
--- a/admin/gentoo/purge-distfiles
+++ b/admin/gentoo/purge-distfiles
@@ -1,7 +1,12 @@
 #!/bin/bash
+# Cleanup script for Portage distfiles
 
-# Source some useful functions
-source ${0%/*}/../../bash/functions/die
+
+# Source required modules (bashmod first, then use it for the others)
+[[ ! -r "${BASH_MODULES_SCRIPT=${0%/*}/../../bash/functions/bashmod}" ]] && { echo "Error: This script requires the 'bashmod' module, please specify its path
+       with the BASH_MODULES_SCRIPT environment variable." ; exit 255 ; }
+source "$BASH_MODULES_SCRIPT"
+bashmod die
 
 # Help message
 if [[ "$1" == "-h" || "$1" == "--help" ]]
