Get rid of bashmod
Since bashmod is a bit convoluted and all scripts usually ever have in
common is a subset of bash/modules/die, just remove all that bashmod
crap and add a minimal die() implementation to all scripts that need it.

Also remove bash/modules/gnupg (unused), move bash/modules/tilde to
admin/check-hardlinks (its only user), and rename bash/modules to
bash/functions.

diff --git a/admin/check-hardlinks b/admin/check-hardlinks
--- a/admin/check-hardlinks
+++ b/admin/check-hardlinks
@@ -29,18 +29,45 @@
 # Build full name
 [[ "${0:0:1}" == "/" ]] && full_0="$0" || full_0="$PWD/$0"
 
-# Source required modules (bashmod first, then use it for the others)
-[[ ! -r "${BASH_MODULES_SCRIPT=${full_0%/*}/../bash/modules/bashmod}" ]] && { echo "Error: This script requires the 'bashmod' module, please specify its path
-       with the BASH_MODULES_SCRIPT environment variable." ; exit 255 ; }
-source "$BASH_MODULES_SCRIPT"
-bashmod die
-bashmod tilde
+# Enable extended globbing, required for tilde()
+shopt -s extglob
+
 
 # Define some constants
 version=0.6b
 
 
 # Define some helper functions
+
+# die: print an error message and exit
+function die() { # *:message
+    printf "Error: %s\n" "$*"
+    exit 1
+} >&2
+
+# tilde: perform tilde expansion on a string
+function tilde() {
+    # NB: Upon error, tilde outputs its input string as is and returns a non-0 error code
+    #     This means that in any case, tilde's output is still safe to use
+
+    # Get the pattern to expand
+    local PREFIX="${1%%/*}"
+    # Make sure there's actually a tilde to expand
+    # /!\ To be on the safe side, only accept paths composed of a restricted set of characters!
+    [[ "$PREFIX" == ~*([[:alnum:]_-]) ]] || { echo "$1" ; return 1 ; }
+    # Perform expansion with/without trailing path
+    if [[ "$PREFIX" == "$1" ]]
+    then
+        # Expansion is left to Bash, to ensure Bash-like behavior
+        eval echo $PREFIX
+    else
+        # Expansion is left to Bash, to ensure Bash-like behavior
+        eval echo -n $PREFIX
+        # Print the remainder of the path as is
+        echo "/${1#*/}"
+    fi
+}
+
 # checklog: log an aligned message about some checked file and update the global return code
 function checklog() { # 1:code 2:message 3:file 4:reference
     local malign=23                  # Message alignment
@@ -140,7 +167,7 @@ fi
 
 # Process options
 getopt -T &> /dev/null
-(( $? != 4 )) && die -r128 "your getopt version is too old, get the enhanced getopt from util-linux!"
+(( $? != 4 )) && die "your getopt version is too old, get the enhanced getopt from util-linux!"
 getopt="$(getopt -n "${0##*/}" -l fix-broken,no-colors,fix-diverged,diff::,fix,fix-missing,quiet,fix-unreachable,version -o +bcdD::fmquV -- "$@")"
 (( $? != 0 )) && exit 128
 eval set -- "$getopt"
@@ -174,16 +201,16 @@ do
             shift
             break
             ;;
-        *) die -r128 "internal error!" ;;
+        *) die "internal error!" ;;
     esac
     shift
 done
 # Test for remaining arguments
-(( $# < 1 )) && die -r128 "missing hardlinks file"
+(( $# < 1 )) && die "missing hardlinks file"
 # Test for valid hardlinks files
 for f in "$@"
 do
-    [[ ! -r "$f" ]] && die -r128 "invalid hardlinks file '$f'"
+    [[ ! -r "$f" ]] && die "invalid hardlinks file '$f'"
 done
 
 # For each hardlinks file
@@ -306,4 +333,3 @@ done
 
 # Return the global return code
 exit $rc
-
diff --git a/admin/gentoo/purge-distfiles b/admin/gentoo/purge-distfiles
--- a/admin/gentoo/purge-distfiles
+++ b/admin/gentoo/purge-distfiles
@@ -5,11 +5,11 @@
 # Build full name
 [[ "${0:0:1}" == "/" ]] && FULL_0="$0" || FULL_0="$PWD/$0"
 
-# Source required modules (bashmod first, then use it for the others)
-[[ ! -r "${BASH_MODULES_SCRIPT=${FULL_0%/*}/../../bash/modules/bashmod}" ]] && { echo "Error: This script requires the 'bashmod' module, please specify its path
-       with the BASH_MODULES_SCRIPT environment variable." ; exit 255 ; }
-source "$BASH_MODULES_SCRIPT"
-bashmod die
+# Functions
+die() { # *:message
+    printf "Error: %s\n" "$*"
+    exit 1
+} >&2
 
 # Help message
 if [[ "$1" == "-h" || "$1" == "--help" ]]
@@ -35,7 +35,7 @@ STATUS=$?
 SIZE=$(echo "$SIZE" | tail -n 1 | cut -f1)
 if [[ $STATUS != 0 ]]
 then
-    [[ $SIZE == 0 ]] && die -i -r0 "Directory $DISTDIR is empty."
+    [[ $SIZE == 0 ]] && { echo "Directory $DISTDIR is empty."; exit 0; }
     die "failed to stat contents of $DISTDIR"
 fi
 
@@ -44,4 +44,3 @@ echo -n "Purge $DISTDIR? ($SIZE) [y/N] "
 declare -u ANS
 read ANS
 [[ "$ANS" == "Y" ]] && rm -Rf "$DISTDIR"/*
-
diff --git a/audio/freebox-title-fix b/audio/freebox-title-fix
--- a/audio/freebox-title-fix
+++ b/audio/freebox-title-fix
@@ -4,11 +4,6 @@
 # Build full name
 [[ "${0:0:1}" == "/" ]] && full_0="$0" || full_0="$PWD/$0"
 
-# Source required modules (bashmod first, then use it for the others)
-[[ ! -r "${BASH_MODULES_SCRIPT=${full_0%/*}/../bash/modules/bashmod}" ]] && { printf "Error: This script requires the 'bashmod' module, please specify its path\n       with the BASH_MODULES_SCRIPT environment variable.\n" ; exit 255 ; }
-source "$BASH_MODULES_SCRIPT"
-bashmod die
-
 if (( $# < 1 )) || [[ "$1" =~ ^(-h|--help)$ ]]
 then
     cat <<- EOF
@@ -36,6 +31,11 @@ then
 	EOF
     exit
 fi
+
+function die() { # *:message
+    printf "Error: %s\n" "$*"
+    exit 1
+} >&2
 
 function require() {    #1:tool [2:variable] [3+:paths]
     local tool="$1"
@@ -90,7 +90,7 @@ shopt -s nocasematch
 
 # Parse command line
 getopt -T &> /dev/null
-(( $? != 4 )) && die -r128 "your getopt version is too old, get the enhanced getopt from util-linux!"
+(( $? != 4 )) && die "your getopt version is too old, get the enhanced getopt from util-linux!"
 getopt="$(getopt -n "${0##*/}" -l quiet,reverse -o qR -- "$@")"
 (( $? != 0 )) && exit 128
 eval set -- "$getopt"
@@ -104,13 +104,13 @@ do
         -q|--quiet) quiet=true ;;
         -R|--reverse) reverse=true ;;
         --) shift ; break ;;
-        *) die -r128 "internal error!" ;;
+        *) die "internal error!" ;;
     esac
     shift
 done
 
 # Process directories
-(( $# < 1 )) && die -r128 "missing directories"
+(( $# < 1 )) && die "missing directories"
 for d in "$@"
 do
     if ! [[ -d "$d" ]]
diff --git a/audio/sedaflac b/audio/sedaflac
--- a/audio/sedaflac
+++ b/audio/sedaflac
@@ -4,10 +4,11 @@
 # Build full name
 [[ "${0:0:1}" == "/" ]] && full_0="$0" || full_0="$PWD/$0"
 
-# Source required modules (bashmod first, then use it for the others)
-[[ ! -r "${BASH_MODULES_SCRIPT=${full_0%/*}/../bash/modules/bashmod}" ]] && { printf "Error: This script requires the 'bashmod' module, please specify its path\n       with the BASH_MODULES_SCRIPT environment variable.\n" ; exit 255 ; }
-source "$BASH_MODULES_SCRIPT"
-bashmod die
+# Functions
+die() { # *:message
+    printf "Error: %s\n" "$*"
+    exit 1
+} >&2
 
 if (( $# < 2 )) || [[ "$1" =~ ^(-h|--help)$ ]]
 then
@@ -25,7 +26,7 @@ fi
 
 # Parse command line
 getopt -T &> /dev/null
-(( $? != 4 )) && die -r128 "your getopt version is too old, get the enhanced getopt from util-linux!"
+(( $? != 4 )) && die "your getopt version is too old, get the enhanced getopt from util-linux!"
 getopt="$(getopt -n "${0##*/}" -l dry-run,verbose -o nv -- "$@")"
 (( $? != 0 )) && exit 128
 eval set -- "$getopt"
@@ -39,13 +40,13 @@ do
         -n|--dry-run) dryrun=true ;;
         -v|--verbose) verbose=true ;;
         --) shift ; break ;;
-        *) die -r128 "internal error!" ;;
+        *) die "internal error!" ;;
     esac
     shift
 done
 
 # Process arguments
-(( $# < 2 )) && die -r128 "missing script and/or file"
+(( $# < 2 )) && die "missing script and/or file"
 sedscript="$1"
 shift
 
diff --git a/bash/functions/todo b/bash/functions/todo
--- a/bash/functions/todo
+++ b/bash/functions/todo
@@ -1,13 +1,11 @@
 #!/bin/bash
-# todo - main function for the todo module
+# todo - print directory todos upon directory change
 
 function todo() {
     # Test for utilities and load modules
-    command -v bashmod &> /dev/null || { echo "Error: missing utility 'bashmod'" ; return 1 ; }
-    bashmod die || { echo "Error: missing Bash module 'die'" ; return 1 ; }
-    command -v getopt &> /dev/null || { echo "Error: missing utility 'getopt'" ; return 1 ; }
+    command -v getopt &> /dev/null || { printf "Error [%s]: %s\n" "$FUNCNAME" "missing utility 'getopt'" >&2; return 1 ; }
     getopt -T &> /dev/null
-    (( $? == 4 )) || die "your getopt version is too old, get the enhanced getopt from util-linux!"
+    (( $? == 4 )) || { printf "Error [%s]: %s\n" "$FUNCNAME" "your getopt version is too old, get the enhanced getopt from util-linux!" >&2; return 1; }
 
     # Define constants
     local version=0.1
@@ -48,6 +46,8 @@ function todo() {
 				    -q|--quiet      don't display an error message if the
 				                    directory contains no TODO file
 				
+				Environment variables:
+				  TODO_FILENAME     TODO filename (default: TODO)
 				_EOF_
 
                 return 0
@@ -62,7 +62,10 @@ function todo() {
                 shift
                 break
                 ;;
-            *) die "internal error!" ;;
+            *)
+                printf "Error [%s]: %s\n" "$FUNCNAME" "internal error!" >&2
+                return 1
+                ;;
         esac
         shift
     done
@@ -83,11 +86,14 @@ function todo() {
                         shift
                         break
                         ;;
-                    *) die "internal error!" ;;
+                    *)
+                        printf "Error [%s]: %s\n" "$FUNCNAME" "internal error!" >&2
+                        return 1
+                        ;;
                 esac
                 shift
             done
-            (( $# != 0 )) && die "too many arguments"
+            (( $# == 0 )) || { printf "Error [%s]: %s\n" "$FUNCNAME" "too many arguments" >&2; return 1; }
 
             # Resolve the 'toggle' action
             [[ "$action" == "toggle" ]] && { [[ "$(type -t cd)" == "function" ]] && action=off || action=on ; }
@@ -128,11 +134,14 @@ function todo() {
                         shift
                         break
                         ;;
-                    *) die "internal error!" ;;
+                    *)
+                        printf "Error [%s]: %s\n" "$FUNCNAME" "internal error!" >&2
+                        return 1
+                        ;;
                 esac
                 shift
             done
-            (( $# != 0 )) && die "too many arguments"
+            (( $# == 0 )) || { printf "Error [%s]: %s\n" "$FUNCNAME" "too many arguments" >&2; return 1; }
 
             # Print the TODO
             local print_failed=false
@@ -158,7 +167,7 @@ function todo() {
 
         "status")
             # Parse options
-            (( $# != 0 )) && die "too many arguments"
+            (( $# == 0 )) || { printf "Error [%s]: %s\n" "$FUNCNAME" "too many arguments" >&2; return 1; }
 
             # Display status information
             local status
@@ -167,15 +176,12 @@ function todo() {
             ;;
 
         "")
-            die "missing action"
+            printf "Error [%s]: %s\n" "$FUNCNAME" "missing action" >&2
+            return 1
             ;;
         *)
-            die "unknown action '$action'"
+            printf "Error [%s]: %s\n" "$FUNCNAME" "unknown action '$action'" >&2
+            return 1
             ;;
     esac
 }
-
-
-# Enable TODO auto-print
-todo on -q
-
